#+TITLE:       Guest Seminar: Renaud Jardri, MD, PhD
#+AUTHOR:      homanlab
#+EMAIL:       homanlab.zurich@gmail.com
#+DATE:        2019-10-12 Sat
#+URI:         /blog/%y/%m/%d/guest-seminar-renaud-jardri-md-phd
#+KEYWORDS:    seminar, guest, confidence, bayesian inference, positive symptoms
#+TAGS:        seminar, guest, confidence, bayesian inference, positive symptoms
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Circular inference in schizophrenia
#+AVATAR:      https://homanlab.github.io/media/img/jardri1.png

#+ATTR_HTML: width 200px
https://homanlab.github.io/media/img/jardri1.png

* Abstract
Positive symptoms in schizophrenia include a combination of
hallucinations, delusions and disorganized thinking. In a forced-choice
task with varying levels of sensory evidence and prior information,
participants' confidence was best captured by a model with different
degrees of circular inference. Circular inference refers to a corruption
of sensory data by prior information and vice versa, leading us to 'see
what we expect' (through descending loops), to 'expect what we see'
(through ascending loops) or both. Ascending loops were stronger for
patients than controls and correlated with the severity of positive
symptoms while descending loops correlated with the severity of negative
symptoms. In addition, both loops correlated with the level of
disorganized symptoms. The findings suggest that circular inference
might mediate the clinical manifestations of schizophrenia.

* About the speaker
Renaud Jardri is a Professor of Child & Adolescent Psychiatry at the
Lille University School of Medicine, and Associate Faculty in the Group
for Neural Theory, INSERM U-960, at the Ecole Normale Supérieure
Paris. Renaud obtained his MD in 2007 and his PhD in Neuroscience in
2010 at the University of Lille. He did a postdoctoral fellowship from
2009 to 2011 with Sophie Deneve at the Ecole Normale Superieur in
Paris. His main research interests are the exploration of the underlying
neural mechanisms of hallucinations in children, adolescents and adults.

* Details
- Date: 12/6/19
- Time: 3:30 PM CET
- Location: PUK Zurich, H108
- Host: Philipp Homan
	
