#+TITLE:       Guest Seminar: Lena Palaniyappan, MD, PhD
#+AUTHOR:      homanlab
#+EMAIL:       homanlab.zurich@gmail.com
#+DATE:        2020-01-06 Mon
#+URI:         /blog/%y/%m/%d/guest-lena-palaniyappan-md-phd
#+KEYWORDS:    guest, seminar, psychosis, heterogeneity
#+TAGS:        guest, seminar, psychosis, heterogeneity
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Morphological heterogeneity in schizophrenia
#+AVATAR:      https://homanlab.github.io/media/img/lena1.png

#+ATTR_HTML: width 200px
https://homanlab.github.io/media/img/lena1.png

#+ATTR_HTML: :target _blank
We are very excited to host [[https://www.researchgate.net/profile/Lena_Palaniyappan][Lena Palaniyappan]] as the first speaker in
2020 in our remote seminar series. Lena is an expert in first episode
psychosis and has just published a series of exciting papers on the
heterogeneity problem in schizophrenia. The seminar will take place on
January 10, 2020, at 3:30 pm at the PUK Zurich, Z105.

* Abstract
The major emphasis of Lena's work is on applying brain imaging to
investigate symptom burden, treatment response and prognostic accuracy
both in psychotic disorders. The clinical goal of this approach is to
understand the pathways that lead to poor long-term outcome in certain
individuals with serious mental disorders. His group concentrates on
understanding the intrinsically organized, largescale brain networks in
psychosis.

* About the speaker
Lena is an associate professor in the Departments of Medical Biophysics
and Psychiatry and a Scientist at Robarts Research Institute. He is a
clinician-scientist with a training background in psychology,
neuroimaging and systems approach in neuroscience. He trained as a
physician and psychiatrist in India and the UK and serves as the
Director of the Prevention and Early Intervention Program for Psychosis
at the London Health Sciences Centre. Lena is one of the leaders in the
field in first episode psychosis and was named a Rising Star by the
Schizophrenia International Research Society in 2018.

* Details
- Date: 01/10/20
- Time: 3:30 PM CET
- Location: PUK Zurich, Z105
- Host: Philipp Homan
	
