#+TITLE:       Guest Seminar: Lara Wallenwein
#+AUTHOR:      homanlab
#+EMAIL:       homanlab.zurich@gmail.com
#+DATE:        2020-05-20 Wed
#+URI:         /blog/%y/%m/%d/guest-seminar-lara-wallenwein
#+KEYWORDS:    seminar, guest, student, pet 
#+TAGS:        seminar, guest, student, pet
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Task-induced changes in FDG uptake
#+AVATAR:      https://homanlab.github.io/media/img/idp_lw.png

#+ATTR_HTML: width 200px
https://homanlab.github.io/media/img/idp_lw.png

#+ATTR_HTML: :target _blank
We are very happy to host Lara Wallenwein in our remote seminar
series. Lara is a master's student in clinical psychology and cognitive
neuroscience at the LMU Munich. The seminar will take place remotely on
May 22, 2020, at 3:30 pm.

* Abstract
Positron Emission Tomography (PET) using 18F-Fluorodeoxyglucose (FDG) as
radiotracer is a powerful tool to assess glucose metabolism, thus
allowing for a direct and quantifiable measure of neuronal activity. The
bolus injection protocol is based on a steady state assumption, implying
that the distribution of FDG uptake remains stable after an uptake
period of approximately 30 min (Varrone et al., 2009). Controversially,
a few studies found differences between subsequently acquired PET images
at 60 min post-injection (p.i.) compared to 70 min p.i. (Ishii et al.,
2006). To test for task-induced changes in FDG uptake, data of 49
middle-aged participants were analyzed. Imaging data were acquired
within an independent research project in a hybrid PET/MR scanner at 30
to 90 min p.i. in list mode.  Participants were scanned twice to analyze
the effects of cognitive training intervention within the independent
research project. Per scanning session two resting-state FDG-PET images
representing cumulative FDG uptake from 42 min p.i. to 50min p.i (Rest1)
and 50 min p.i. to 58 min p.i.(Rest2) were obtained. Additionally, one
FDG-PET image representing FDG uptake whilst performing a working memory
task from 60 min p.i. to 68 min p.i. (Task1) was acquired. Regional
differences in FDG uptake were analyzed on a whole brain level, using a
2 x 3 ANOVA design with 2 Timepoints and 3 Brain States (i.e. Rest1,
Rest2 and Task1) with global normalization. The task contrast (Task1 >
Rest2) revealed mixed task- and time- induced changes in FDG uptake in
frontal and parietal areas as well as in dorsal anterior cingulate
cortex, and putamen. The rest contrast (Rest2 > Rest1), representing
only time- induced FDG uptake variations, revealed significant
differences mainly in medial frontal and temporal areas, and putamen. To
isolate task-induced FDG uptake, a contrast of contrast was computed,
comparing the task contrast to the rest contrast (i.e. Task1 > Rest2 >>
Rest2 > Rest1). This analysis revealed significant increase in FDG
uptake within clusters in frontal lobe, inferior parietal cortex, left
precentral gyrus, posterior-, and dorsal anterior cingulate
cortex. These are regions known to be involved in WM processing (Owen et
al., 2005). Simultaneously acquired task fMRI data will be analyzed
accordingly to study the overlap between fMRI and FDG-PET derived WM
task activations. This study is the first to show

* About the speaker
Lara is a master's student in clinical psychology and cognitive
neuroscience at the LMU Munich, working with Lana Kambeitz-Ilankovic and
Igor Yakushev. She is interested in multimodal imaging of normal and
pathological cognition.
	
* Details
- Date: 05/22/20
- Time: 3:30 PM CET
- Location: Remote via Zoom
- Host: Philipp Homan
	
