#+TITLE:       Guest Seminar: Steven Silverstein, PhD
#+AUTHOR:      Philipp Homan
#+EMAIL:       philipp.homan@bli.uzh.ch
#+DATE:        2019-10-03 Thu
#+URI:         /blog/%y/%m/%d/guest-seminar-steven-silverstein-phd
#+KEYWORDS:    guest, seminar, optical coherence tomography, retina
#+TAGS:        guest, seminar, optical coherence tomography, retina
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Steven Silverstein's remote lecture on OCT
#+AVATAR:      https://homanlab.github.io/media/img/oct1.png

#+ATTR_HTML: width 200px
https://homanlab.github.io/media/img/oct1.png

* Abstract
Dr. Silverstein (University of Rochester) will discuss the nature of
optical coherence tomography (OCT), as well as the rationale for using
it in clinical research on people with schizophrenia. He will also
summarize findings from this field, including his own published and
recent unpublished data. Finally, he will discuss potential confounds in
OCT research in schizophrenia that need to be considered in strong study
designs.

* About the speaker
[[https://www.urmc.rochester.edu/psychiatry/news.aspx][Steven Silverstein, PhD]],
has been named the the George L. Engel Professor in
Psychosocial Medicine and associate chair of Research for the department
of Psychiatry at the University of Rochester Medical Center. He will
join the University of Rochester in January 2020. Dr. Silverstein is an
expert in the use of OCT in schizophrenia spectrum disorders and has
published [[https://www.cambridge.org/core/journals/psychological-medicine/article/optical-coherence-tomography-indices-of-structural-retinal-pathology-in-schizophrenia/9060C9830CBEEE8CE0AD7B36E4754F6D][important new findings]] in 2018.

* Details
- Date: 10/11/19
- Time: 3:30 PM CET
- Location: PUK Zurich, H108
- Host: Philipp Homan
